# Custom Language File for Launcher Customizer

[ejs.app]
title = "탱커전공의 RPG서버"

[ejs.landing]
mediaGitHubURL = "https://github.com/Kali0712/RPGServer"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/Kali0712/RPGServer"
supportLink = "https://github.com/Kali0712/RPGServer/issues"

[ejs.welcome]
welcomeHeader = "탱커전공의 RPG서버에 오신 것을 환영합니다!"
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
